formatter: markdown table
header-from: header.tf

content: |-
  {{ .Header }} 

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}
     
  {{ .Outputs }}

  ## Variables

  ```hcl
  {{ include "locals.tf" }}
  ```

  {{ .Footer }}

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

sort:
  enabled: true
  by: required

settings:
  indent: 2
  required: true
